---
title: "NHL Goalie and Skater Heat Maps"
author: "Sasank Vishnubhatla"
date: "January 10, 2019"
html_document:
  runtime: shiny
  theme: simplex
  df_print: paged
  dev: 'svg'
pdf_document:
  df_print: kable
  toc: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

Last Update: `r Sys.time()`

GitHub Repository: [sv4u/goalie-and-skater-heat-maps](https://github.com/sv4u/goalie-and-skater-heat-maps)

# Introduction

In the NHL, players have their "sweet-spots". For skaters, it can be the top of a certain circle, or right in-front of the net. For goalies, it could be where their vision is best and where they have the best angle to cut down a shot. All players have these sweet-spots, but it is difficult to analytically say where they are. By using shot location data, we can determine these locations and create models show where goalies and skaters need improvement and where they succeed.

# Data Formatting

To start, we need to read in our data. Our data is formatted nicely in CSV format. We have data from the 2016-2017 season, 2017-2018 season, and 2018-2019 season (up to 1/7/19). This data was downloaded from [MoneyPuck](http://www.moneypuck.com).

# Function Definitions {.tabset .tabset-fade}

## Generic

## Goalies

## Skaters

# Analysis {.tabset .tabset-fade}

## Goalies {.tabset .tabset-fade}

### Matt Murray

### Casey DeSmith

### Marc-Andre Fleury

### Andrei Vasilevskiy

### Carey Price

### Braden Holtby

### John Gibson

## Skaters {.tabset .tabset-fade}

### Sidney Crosby

### Evgeni Malkin

### Alex Ovechkin

### Nikita Kucherov

### Jake Guentzel

### Erik Karlsson

### Kris Letang
